### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ayoraind** [gtonkinhill/tracs#8]
Dear Tracs developers,

Thank you for this tool. I installed Tracs via bioconda as instructed in the section on installation. However, on trying `tracs align -h` or any of the tracs modules, I encountered the error `Illegal instruction (core dumped)`. Is there a bug, or did I do something wrong?

**Comment by gtonkinhill** [comment]
Hi,

This sounds like something went wrong in the installation. It's quite hard to debug these issues remotely but we will try to install TRACS on a few other systems to see if we can reproduce the problem.

**Comment by ayoraind** [comment]
@gtonkinhill,

I just noted that the issue has been corrected in the recent version (v1.0.1). Thanks. The issue can be closed now.
